version: '3.8'

services:
  postgres:
    container_name: postgres-1
    image: postgres
    environment:
      POSTGRES_USER: kalemz
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: library
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - library
    restart: unless-stopped

networks:
  library:
    driver: bridge

volumes:
  postgres:
    driver: local